image: docker:stable

stages:
  - build

before_script:
  - export IMAGE_PREFIX=`[ ! -z $CI_MERGE_REQUEST_ID ] && echo "MR$CI_MERGE_REQUEST_ID" || echo $CI_COMMIT_REF_NAME`
  - export IMAGE_TAG=$IMAGE_PREFIX`[ ! -z $CI_COMMIT_TAG ] && echo "" || echo "-$CI_COMMIT_SHORT_SHA"`
  - export LATEST_IMAGE_TAG=`[ -z $CI_COMMIT_TAG ] && echo "$IMAGE_PREFIX-" || echo ''`latest
  - export RELEASE=`[[ ! -z $CI_COMMIT_TAG ]] && echo "$CI_COMMIT_TAG" || echo "$CI_COMMIT_SHORT_SHA"`

.docker:
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg VERSION=$RELEASE --build-arg API_URL=$API_URL -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker tag $CI_REGISTRY_IMAGE:$IMAGE_TAG $CI_REGISTRY_IMAGE:$LATEST_IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:$LATEST_IMAGE_TAG

docker_staging:
  extends: .docker
  environment: staging
  only:
    - release

docker_production:
  extends: .docker
  environment: production
  only:
    - tags
